version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: project-pulse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DeveloperMagang123
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/be
    env_file:
      - ./backend/be/.env
    depends_on:
      - db
    ports:
      - "8000:8000"

  web:
    build:
      context: ./web
    environment:
      VITE_API_URL: http://localhost:8000/api
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  db_data:
